### PR TITLE
Added onFailure callback for JSON requests

### PR DESCRIPTION
**Pull request by fedemoretti**
It is sometimes useful to have a callback for failing requests.
In some cases, the error does not matter, but you actually want to know if the request has failed. I found this callback very useful in my projects since it allows me to handle weird failure cases.

### CODE REVIEW

**Comment by smarek** [comment]
Do I understand correclty, that this would cause the library to call multiple onFailure callbacks on failure on single request/response hadling? If that's correct, this won't be merged, it's not good design principle.

**Comment by fedemoretti** [comment]
Hi Marek, what you stated makes sense. The idea behind these changes was to be able to handle failure when the error was not important. For example, I've used APIs where an error response contained some JSON data in the body about the specific error, but sometimes the request just failed and HTML was sent in the body (500 internal error?). In those cases, I didn't want to override all the onFailure methods of JsonHttpResponseHandler, so I created this new callback that gets fired on every failing request.

I know 2 onFailure callbacks are triggered, and that does not seem to be fine.
What are your thoughts about this? Do you have any other idea to accomplish what I described?

Thanks in advance,
Federico.

**Comment by smarek** [comment]
I think that makes sense, but should be implemented other way around.
Something like check if the proper callback was implemented/overriden by subclass, and if not call common onFailure method, and if that's not implemented also, log the "not overriden" error

What do you think?

**Comment by smarek** [comment]
Also, JsonHttpResponseHandler is kind of old, if I were you, I'd go for using [`BaseJsonHttpResponseHandler`](https://github.com/loopj/android-async-http/blob/master/library/src/main/java/com/loopj/android/http/BaseJsonHttpResponseHandler.java), which is demonstrated in Sample application too.

**Comment by fedemoretti** [comment]
You are right, [BaseJsonHttpResponseHandler](https://github.com/loopj/android-async-http/blob/master/library/src/main/java/com/loopj/android/http/BaseJsonHttpResponseHandler.java) was exactly what I was looking for.
I'll close this PR since this class has the exact behavior I was trying to achieve.

Thanks!

**Pull request closed without merging**
