### PR TITLE
Feature of Support Session imported.

### PR DESCRIPTION
**Pull request by LittlePanpc**
One option was added, which users of  'android-async-http' could select to support session or not, just by one simple line of codes. For example, AsyncHttpClient.setKeepSessionId(true/false);

### CODE REVIEW

**Comment by smarek** [comment]
I don't see the purpose of this, simply by using CookieStore (see [`setCookieStore` method](https://github.com/loopj/android-async-http/blob/master/library/src/main/java/com/loopj/android/http/AsyncHttpClient.java#L353)) will keep the session cookies if remote server sets them properly.

or am i wrong?

**Comment by LittlePanpc** [comment]
@smarek 
Give me some time, I will figure it out.
I will test whether the session requirement could be implemented by CookieStore.

**Comment by LittlePanpc** [comment]
@smarek 
Alright, you are right. simply by using setCookieStore will keep the session cookies if remote server sets them properly. But there still is a question in my mind. Where have ever CookieStore stored "sessionid" or something like that which are setted by remote server, disk, memory or anywhere else? Have the source codes of CookieStore implemented this?

**Comment by smarek** [comment]
@LittlePanpc just look into specific implementation. Only implementation provided by us is [PersistentCookieStore.java](https://github.com/loopj/android-async-http/blob/master/library/src/main/java/com/loopj/android/http/PersistentCookieStore.java), which persists data into SharedPreferences (so disk), other implementations will be different.

**Pull request closed without merging**
