### PR TITLE
Support for TLSv1.1 and TLSv1.2 only servers

### PR DESCRIPTION
**Pull request by XYG6**
Using a webserver with only TLSv1.1 and/or TLSv1.2 enabled, it is impossible to connect to it using android-async-http. I found a solution on another project having a similar issue (https://github.com/owncloud/android/issues/362) by enabling all secure and supported protocols. Credits to https://github.com/sztyler

### CODE REVIEW

**Comment by stvn** [comment]
Is this something that you guys are fixing? is this something that you are going to accept the merge request for once the minSDK version is updated?  Is this resolved in the 1.4.9 release?  Please advise.

**Comment by smarek** [comment]
@stvn i think it's very likely we'll update the minSdkVersion because keeping compatibility with API 3 is still possible with recent versions of this library

**Comment by kbala** [comment]
@smarek is this a fix for #744 SSL Socket Read Time Out ?

**Comment by AlexanderLS** [comment]
@XYG6 , @eTryp your commits were merged into https://github.com/Vorlonsoft/AndroidAsyncHTTP

@stvn , @kbala fixed in https://github.com/Vorlonsoft/AndroidAsyncHTTP

**Pull request merged**
