### PR TITLE
Make SecureSocketFactory verify hostnames

### PR DESCRIPTION
**Pull request by nullEuro**
see #816

### CODE REVIEW

**Comment by smarek** [comment]
Hey, according to the docs, 
https://developer.android.com/training/articles/security-ssl.html#WarningsSslSocket
[https://developer.android.com/reference/javax/net/ssl/HostnameVerifier.html#verify(java.lang.String, javax.net.ssl.SSLSession)](https://developer.android.com/reference/javax/net/ssl/HostnameVerifier.html#verify(java.lang.String, javax.net.ssl.SSLSession))

This method does not throw exception if hostname does not match the certificate hostname, instead it returns boolean that should be handled by application, see the snippet in first link.

Can you please verify and possibly fix the pull request?

**Comment by nullEuro** [comment]
No, this is only for the overload with `SSLSession` as a second parameter, not `SSLSocket`. The decision for this inconsistent and possibly dangerous behavior is beyond me.
I have tested my solution and it works throws an exception if the hostname does not match.

**Comment by smarek** [comment]
@nullEuro cool, sorry about not-testing the solution first :-)
Also, you're missing import, see the bottom of build log: https://travis-ci.org/loopj/android-async-http/builds/53037696

I'll merge it as soon as you pass the travis build :+1:

**Comment by nullEuro** [comment]
Oh snap, quick copypasta ;-) Fixed and squashed commits

**Comment by smarek** [comment]
Thank you very much! merging and closing related issue

**Comment by fineswap** [comment]
Thanks @nullEuro for this and great job! :)

**Comment by nullEuro** [comment]
You're welcome!

**Pull request merged**
